config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  get 'home/index'

  root to: "home#index"
  

  resources :tasks, except: [:index] do 
    resources :activities
  end

  resources :users

  get '/dashboard' => 'home#dashboard', as: :dashboard

  get '/m-dashboard' => 'home#manager_dashboard', as: :manager_dashboard

  get '/tasks' => 'users#tasks', as: :custom_tasks

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :task
	belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :activities
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %w{ employee manager }

  has_many :tasks
  has_many :activities

  # Role check
  ROLES.each do |role|
    define_method("is_#{role}?") do
      self.role == role 
    end
  end

  # Function to get all activities of a user
  def get_all_activities
  	self.is_manager? ? Activity.all : Activity.joins(:task).where(:tasks => { user_id: self.id })
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /activities
  # GET /activities.json
  def index
    @activities = current_user
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:date, :duration, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    resource.role == "employee" ? dashboard_path : manager_dashboard_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authorize_manager, only: :manager_dashboard
  def index
  end

  def dashboard
  	@activities = current_user.get_all_activities
  end

  def manager_dashboard
  end

  private

  def authorize_manager
  	redirect_to root_path unless current_user.role == "manager"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_manager

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:start_date, :end_date, :status, :planned_hours)
    end

    def authenticate_manager
      redirect_to dashboard_path unless current_user && current_user.is_manager?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tasks
    @tasks = current_user.is_manager? ? Task.all : current_user.tasks
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :role)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.haml
= form_for(@activity) do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2
        = pluralize(@activity.errors.count, "error")
        prohibited this activity from being saved:
      %ul
        - @activity.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :date
    %br/
    = f.date_select :date
  .field
    = f.label :duration
    %br/
    = f.number_field :duration
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/activities/edit.html.haml
.container
	%h1 Editing Activity
	= render 'form'
	= link_to 'Show', @activity
	|
	= link_to 'Back', activities_path

app/views/activities/index.html.haml
.container
  %p#notice= notice
  %h1 Listing Activities
  %table
    %thead
      %tr
        %th Date
        %th Duration
        %th Description
        %th{:colspan => "3"}
    %tbody
      - @activities.each do |activity|
        %tr
          %td= activity.date
          %td= activity.duration
          %td= activity.description
          %td= link_to 'Show', activity
          %td= link_to 'Edit', edit_activity_path(activity)
          %td= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
.container
	%h1 New Activity
	= render 'form'
	= link_to 'Back', activities_path

app/views/activities/show.html.haml
.conatiner
  %p#notice= notice
  %p
    %strong Date:
    = @activity.date
  %p
    %strong Duration:
    = @activity.duration
  %p
    %strong Description:
    = @activity.description
  = link_to 'Edit', edit_activity_path(@activity)
  |
  = link_to 'Back', activities_path

app/views/home/dashboard.html.haml
.container
  .row
    .col-xs-12
      .pull-right
        = link_to "Tasks", custom_tasks_path, class: "btn btn-success"
  .row
    %h2 Activities
    - if @activities.count < 1
      Sorry You dont have any activity to list
    - else
      .table.table-hover
        .thead
          .tr
            .th Description
            .th Date
            .th Duration
        .tbody
          - @activities.each do |activity|
            .td activity.description
            .td activity.date
            .td activity.duration

app/views/home/index.html.haml
%h1 Task Manager APP, Please signin/signup to Continue

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TestApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: "shared/header"
    = yield

app/views/shared/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#{root_path}"} Task Manager
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-default"
        - else
          %li
            = link_to "Sign Up", new_user_registration_path, class: "btn btn-success"
          %li
            = link_to "Sign In", new_user_session_path, class: "btn btn-success"

app/views/tasks/_form.html.haml
= form_for(@task) do |f|
  - if @task.errors.any?
    #error_explanation
      %h2
        = pluralize(@task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :start_date
    %br/
    = f.date_select :start_date
  .field
    = f.label :end_date
    %br/
    = f.date_select :end_date
  .field
    = f.label :status
    %br/
    = f.text_field :status
  .field
    = f.label :planned_hours
    %br/
    = f.number_field :planned_hours
  .actions
    = f.submit

app/views/tasks/edit.html.haml
.container
	%h1 Editing Task
	= render 'form'
	= link_to 'Show', @task
	|
	= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
.container
  %p#notice= notice
  %h1 Listing Tasks
  %table
    %thead
      %tr
        %th Start date
        %th End date
        %th Status
        %th Planned hours
        %th{:colspan => "3"}
    %tbody
      - @tasks.each do |task|
        %tr
          %td= task.start_date
          %td= task.end_date
          %td= task.status
          %td= task.planned_hours
          %td= link_to 'Show', task
          %td= link_to 'Edit', edit_task_path(task)
          %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
.container
	%h1 New Task
	= render 'form'
	= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
.container
	%p#notice= notice
	%p
	  %strong Start date:
	  = @task.start_date
	%p
	  %strong End date:
	  = @task.end_date
	%p
	  %strong Status:
	  = @task.status
	%p
	  %strong Planned hours:
	  = @task.planned_hours
	= link_to 'Edit', edit_task_path(@task)
	|
	= link_to 'Back', tasks_path

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :password
    %br/
    = f.text_field :password
  .field
    = f.label :role
    %br/
    = f.text_field :role
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form'
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
.container
  %p#notice= notice
  %h1 Listing Users
  %table.table-hover
    %thead
      %tr
        %th Name
        %th Email
        %th Password
        %th Role
        %th{:colspan => "3"}
    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= user.password
          %td= user.role
          %td= link_to 'Show', user, class: 'btn btn-success'
          %td= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning'
          %td= link_to 'Destroy', user, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  = link_to 'New User', new_user_path, class: 'btn btn-success'

app/views/users/new.html.haml
%h1 New User
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @user.name
%p
  %strong Email:
  = @user.email
%p
  %strong Password:
  = @user.password
%p
  %strong Role:
  = @user.role
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path

app/views/users/tasks.html.haml
.container
  .col-xs-12
    .row
      .pull-right
        = link_to "Create Task", new_task_path, class: "btn btn-success" if current_user.is_manager?
    .row
      %h2 Tasks
      - if @tasks.count < 1
        Sorry You dont have any Task to list
      - else
        .table.table-hover
          .thead
            .tr
              .th S.No
              .th Start Date
              .th End Date
              .th Status
              .th Planned Hours
              .th Action
          .tbody
            - @tasks.each do |task|
              .td task.id
              .td task.start_date
              .td task.end_date
              .td task.status
              .td task.planned_hours
              .td 